<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <Reference
                Include="C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\10.0.1\*.dll"
                Exclude="C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\10.0.1\aspnetcorev2_inprocess.dll">
            <Private>False</Private>
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <Content Remove="wwwroot\**" />
        <EmbeddedResource Include="wwwroot\**\*" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" />
    </ItemGroup>
    <ItemGroup>
      <_ContentIncludedByDefault Remove="Properties\launchSettings.json" />
    </ItemGroup>
</Project>